/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2018-02-06 00:08:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ar.edu.ubp.pdc.fdeschant.examen.RecursosBean;
import java.util.LinkedList;

public final class lista_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tld/customs.tld", Long.valueOf(1517863122428L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ar.edu.ubp.pdc.fdeschant.examen.RecursosBean");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/utils.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/main.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/main.css\"/>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Recursos</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<p> Recursos </p>\r\n");
      out.write("<table>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Recursos</th>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">Propietarios</th>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">nro recurso</th>\r\n");
      out.write("\t\t\t\t\t<th align=\"left\">vigente</th>\r\n");
      out.write("\t\t\t\t\t<th>&nbsp;</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t");

	
	LinkedList<RecursosBean> lista =(LinkedList<RecursosBean>)(request.getAttribute("lista"));
	for(int i= 0; i<lista.size();i++) {
		RecursosBean rec= lista.get(i);
		
	
      out.write("\r\n");
      out.write("\t\t<tr id=\"");
      out.print( (i%2==0? "even":"odd"));
      out.write("\">\r\n");
      out.write("\t\t\t<td>");
      //  ct:temas
      ar.edu.ubp.pdc.fdeschant.examen.RecursosTagHandler _jspx_th_ct_005ftemas_005f0 = new ar.edu.ubp.pdc.fdeschant.examen.RecursosTagHandler();
      _jsp_getInstanceManager().newInstance(_jspx_th_ct_005ftemas_005f0);
      try {
        _jspx_th_ct_005ftemas_005f0.setJspContext(_jspx_page_context);
        // /lista.jsp(36,7) name = todos type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005ftemas_005f0.setTodos("N");
        // /lista.jsp(36,7) name = tipoRecurso type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005ftemas_005f0.setTipoRecurso(rec.getCod_tipo_recurso() );
        // /lista.jsp(36,7) name = nombre type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005ftemas_005f0.setNombre("");
        _jspx_th_ct_005ftemas_005f0.doTag();
      } finally {
        _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005ftemas_005f0);
      }
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      //  ct:propietario
      ar.edu.ubp.pdc.fdeschant.examen.PropietariosTagHandler _jspx_th_ct_005fpropietario_005f0 = new ar.edu.ubp.pdc.fdeschant.examen.PropietariosTagHandler();
      _jsp_getInstanceManager().newInstance(_jspx_th_ct_005fpropietario_005f0);
      try {
        _jspx_th_ct_005fpropietario_005f0.setJspContext(_jspx_page_context);
        // /lista.jsp(37,7) name = tipoPropietario type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005fpropietario_005f0.setTipoPropietario(rec.getTipo_propietario() );
        // /lista.jsp(37,7) name = nombre type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005fpropietario_005f0.setNombre("");
        // /lista.jsp(37,7) name = idArea type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005fpropietario_005f0.setIdArea(rec.getNro_area() );
        // /lista.jsp(37,7) name = idPersonal type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_ct_005fpropietario_005f0.setIdPersonal(rec.getNro_leg_personal() );
        _jspx_th_ct_005fpropietario_005f0.doTag();
      } finally {
        _jsp_getInstanceManager().destroyInstance(_jspx_th_ct_005fpropietario_005f0);
      }
      out.write(' ');
      out.write(' ');
      out.print(rec.getDesc_recurso() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(rec.getNro_recurso() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(rec.getVigente() );
      out.write("</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<a href=\"./guardar\" onclick=\"jFinal.Guardar();\">Guardar</a>\r\n");
      out.write("<a href=\"./index.jsp\"> Cancelar</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
