
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.fds.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-27T18:20:22.260-03:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ListaObrasSocialesCXFService",
                      portName = "ListaObrasSocialesCXFPort",
                      targetNamespace = "http://cxf.fds.das.ubp.edu.ar/",
                      wsdlLocation = "http://localhost:8091/RecuperatorioServerCXF/ListaObrasSocialesCXF?wsdl",
                      endpointInterface = "ar.edu.ubp.das.fds.cxf.ListaObrasSocialesCXF")
                      
public class ListaObrasSocialesCXFPortImpl implements ListaObrasSocialesCXF {

    private static final Logger LOG = Logger.getLogger(ListaObrasSocialesCXFPortImpl.class.getName());

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.fds.cxf.ListaObrasSocialesCXF#getObrasSociales()*
     */
    public java.util.List<java.lang.String> getObrasSociales() throws Exception_Exception   { 
        LOG.info("Executing operation getObrasSociales");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-7327404";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
