
package ar.edu.ubp.das.fdeschant;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T17:47:33.438-03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class Servicio_PortTypeServer{

    protected Servicio_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.fdeschant.Servicio();
        String address = "http://localhost:9090/ServicioPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Servicio_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 