
package ar.edu.ubp.das.fdeschant.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Mon Nov 06 17:47:33 ART 2017
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "getCategoriasResponse", namespace = "http://fdeschant.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCategoriasResponse", namespace = "http://fdeschant.das.ubp.edu.ar/")

public class GetCategoriasResponse {

    @XmlElement(name = "return")
    private java.util.LinkedList<ar.edu.ubp.das.fdeschant.Categoria> _return;

    public java.util.LinkedList<ar.edu.ubp.das.fdeschant.Categoria> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.LinkedList<ar.edu.ubp.das.fdeschant.Categoria> new_return)  {
        this._return = new_return;
    }

}

