
package ar.edu.ubp.das.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FactorialWSService", targetNamespace = "http://ws.das.ubp.edu.ar/", wsdlLocation = "http://localhost:8091/FactorialJAXWS/FactorialWS?wsdl")
public class FactorialWSService
    extends Service
{

    private final static URL FACTORIALWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTORIALWSSERVICE_EXCEPTION;
    private final static QName FACTORIALWSSERVICE_QNAME = new QName("http://ws.das.ubp.edu.ar/", "FactorialWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/FactorialJAXWS/FactorialWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTORIALWSSERVICE_WSDL_LOCATION = url;
        FACTORIALWSSERVICE_EXCEPTION = e;
    }

    public FactorialWSService() {
        super(__getWsdlLocation(), FACTORIALWSSERVICE_QNAME);
    }

    public FactorialWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTORIALWSSERVICE_QNAME, features);
    }

    public FactorialWSService(URL wsdlLocation) {
        super(wsdlLocation, FACTORIALWSSERVICE_QNAME);
    }

    public FactorialWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTORIALWSSERVICE_QNAME, features);
    }

    public FactorialWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FactorialWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FactorialWS
     */
    @WebEndpoint(name = "FactorialWSPort")
    public FactorialWS getFactorialWSPort() {
        return super.getPort(new QName("http://ws.das.ubp.edu.ar/", "FactorialWSPort"), FactorialWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FactorialWS
     */
    @WebEndpoint(name = "FactorialWSPort")
    public FactorialWS getFactorialWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.das.ubp.edu.ar/", "FactorialWSPort"), FactorialWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTORIALWSSERVICE_EXCEPTION!= null) {
            throw FACTORIALWSSERVICE_EXCEPTION;
        }
        return FACTORIALWSSERVICE_WSDL_LOCATION;
    }

}
