
package ar.edu.ubp.das.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FactorialWS", targetNamespace = "http://ws.das.ubp.edu.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FactorialWS {


    /**
     * 
     * @param nro
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactorial", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetFactorial")
    @ResponseWrapper(localName = "getFactorialResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetFactorialResponse")
    @Action(input = "http://ws.das.ubp.edu.ar/FactorialWS/getFactorialRequest", output = "http://ws.das.ubp.edu.ar/FactorialWS/getFactorialResponse")
    public List<Long> getFactorial(
        @WebParam(name = "nro", targetNamespace = "")
        int nro);

}
