
package asdasd;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T16:12:35.701-03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class cassdadadaServer{

    protected cassdadadaServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new asdasd.casdda();
        String address = "http://localhost:9090/casddaPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new cassdadadaServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 