
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package asdasd;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T16:12:35.701-03:00
 * Generated source version: 3.1.7
 * 
 */
public class cassdadadaClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://asdasd/", "casddaService");
        QName portName = new QName("http://asdasd/", "casddaPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/casddaPort"); 
        asdasd.cassdadada client = service.getPort(portName,  asdasd.cassdadada.class);
        
        // Insert code to invoke methods on the client here
    }

}