
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T17:31:23.176-03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class ICategoriasServer{

    protected ICategoriasServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.CategoriasWS();
        String address = "http://localhost:9090/CategoriasWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ICategoriasServer();
        System.out.println("Server ready..."); 
        
    }
}
 
 