package ar.edu.ubp.das.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T17:38:39.128-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "CategoriasWSService", 
                  wsdlLocation = "http://localhost:9090/CategoriasWSPort?wsdl",
                  targetNamespace = "http://ws.das.ubp.edu.ar/") 
public class CategoriasWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.das.ubp.edu.ar/", "CategoriasWSService");
    public final static QName CategoriasWSPort = new QName("http://ws.das.ubp.edu.ar/", "CategoriasWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/CategoriasWSPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CategoriasWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/CategoriasWSPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CategoriasWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CategoriasWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoriasWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CategoriasWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CategoriasWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CategoriasWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ICategorias
     */
    @WebEndpoint(name = "CategoriasWSPort")
    public ICategorias getCategoriasWSPort() {
        return super.getPort(CategoriasWSPort, ICategorias.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICategorias
     */
    @WebEndpoint(name = "CategoriasWSPort")
    public ICategorias getCategoriasWSPort(WebServiceFeature... features) {
        return super.getPort(CategoriasWSPort, ICategorias.class, features);
    }

}
