package ar.edu.ubp.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T17:38:39.128-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "ICategorias")
@XmlSeeAlso({ObjectFactory.class})
public interface ICategorias {

    @WebMethod(action = "urn:GetCategorias")
    @RequestWrapper(localName = "getCategorias", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetCategorias")
    @ResponseWrapper(localName = "getCategoriasResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetCategoriasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ar.edu.ubp.das.ws.CategoriaBean> getCategorias() throws Exception_Exception;
}
