
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-12T19:32:24.589-03:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "FactorialWSService",
                      portName = "FactorialWSPort",
                      targetNamespace = "http://ws.das.ubp.edu.ar/",
                      wsdlLocation = "http://localhost:9090/FactorialCXFWS/services?wsdl",
                      endpointInterface = "ar.edu.ubp.das.ws.IFactorialWS")
                      
public class FactorialWSPortImpl implements IFactorialWS {

    private static final Logger LOG = Logger.getLogger(FactorialWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.IFactorialWS#getFactorial(int  arg0 )*
     */
    public java.util.List<java.lang.Long> getFactorial(int arg0) { 
        LOG.info("Executing operation getFactorial");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.Long> _return = new java.util.ArrayList<java.lang.Long>();
            java.lang.Long _returnVal1 = Long.valueOf(5400514285105100224l);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
