package ar.edu.ubp.das.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-12T19:32:24.617-03:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "FactorialWSService", 
                  wsdlLocation = "http://localhost:9090/FactorialCXFWS/services?wsdl",
                  targetNamespace = "http://ws.das.ubp.edu.ar/") 
public class FactorialWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.das.ubp.edu.ar/", "FactorialWSService");
    public final static QName FactorialWSPort = new QName("http://ws.das.ubp.edu.ar/", "FactorialWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/FactorialCXFWS/services?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FactorialWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/FactorialCXFWS/services?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FactorialWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FactorialWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FactorialWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FactorialWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FactorialWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FactorialWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IFactorialWS
     */
    @WebEndpoint(name = "FactorialWSPort")
    public IFactorialWS getFactorialWSPort() {
        return super.getPort(FactorialWSPort, IFactorialWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFactorialWS
     */
    @WebEndpoint(name = "FactorialWSPort")
    public IFactorialWS getFactorialWSPort(WebServiceFeature... features) {
        return super.getPort(FactorialWSPort, IFactorialWS.class, features);
    }

}
