
package ar.edu.ubp.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-12T19:32:24.488-03:00
 * Generated source version: 3.1.3
 * 
 */
public final class IFactorialWS_FactorialWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.ubp.edu.ar/", "FactorialWSService");

    private IFactorialWS_FactorialWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FactorialWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FactorialWSService ss = new FactorialWSService(wsdlURL, SERVICE_NAME);
        IFactorialWS port = ss.getFactorialWSPort();  
        
        {
        System.out.println("Invoking getFactorial...");
        int _getFactorial_arg0 = -56119642;
        java.util.List<java.lang.Long> _getFactorial__return = port.getFactorial(_getFactorial_arg0);
        System.out.println("getFactorial.result=" + _getFactorial__return);


        }

        System.exit(0);
    }

}
