package ar.edu.ubp.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-12T19:32:24.608-03:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "IFactorialWS")
@XmlSeeAlso({ObjectFactory.class})
public interface IFactorialWS {

    @WebMethod(action = "urn:GetFactorial")
    @RequestWrapper(localName = "getFactorial", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetFactorial")
    @ResponseWrapper(localName = "getFactorialResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetFactorialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Long> getFactorial(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
