
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-19T19:33:07.549-03:00
 * Generated source version: 3.2.0
 * 
 */
 
public class PaisesWS_PortTypeServer{

    protected PaisesWS_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.PaisesWS();
        String address = "http://localhost:9090/PaisesWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new PaisesWS_PortTypeServer();
        System.out.println("Server ready..."); 
    }
}
 
 