
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T16:09:10.554-03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class yyyyyServer{

    protected yyyyyServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.FactorialWS();
        String address = "http://localhost:9090/FactorialWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new yyyyyServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 