
package ar.edu.ubp.das.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-19T19:41:43.499-03:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.das.ubp.edu.ar/")
public class Exception_Exception extends java.lang.Exception {
    
    private ar.edu.ubp.das.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, ar.edu.ubp.das.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, ar.edu.ubp.das.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public ar.edu.ubp.das.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
