
package ar.edu.ubp.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-19T19:41:43.448-03:00
 * Generated source version: 3.2.0
 * 
 */
public final class PaisesWS_PaisesWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.ubp.edu.ar/", "PaisesWSService");

    private PaisesWS_PaisesWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PaisesWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PaisesWSService ss = new PaisesWSService(wsdlURL, SERVICE_NAME);
        PaisesWS port = ss.getPaisesWSPort();  
        
        {
        System.out.println("Invoking getPaises...");
        try {
            java.util.List<ar.edu.ubp.das.ws.PaisBean> _getPaises__return = port.getPaises();
            System.out.println("getPaises.result=" + _getPaises__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking test...");
        java.lang.String _test__return = port.test();
        System.out.println("test.result=" + _test__return);


        }

        System.exit(0);
    }

}
