
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.ws;

import java.util.LinkedList;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-19T19:41:43.510-03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "PaisesWSService",
                      portName = "PaisesWSPort",
                      targetNamespace = "http://ws.das.ubp.edu.ar/",
                      wsdlLocation = "http://localhost:9090/PaisesWSPort?wsdl",
                      endpointInterface = "ar.edu.ubp.das.ws.PaisesWS")
                      
public class PaisesWSPortImpl implements PaisesWS {

    private static final Logger LOG = Logger.getLogger(PaisesWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.PaisesWS#getPaises()*
     */
    public LinkedList<ar.edu.ubp.das.ws.PaisBean> getPaises() throws Exception_Exception   { 
        LOG.info("Executing operation getPaises");
        try {
        	LinkedList<ar.edu.ubp.das.ws.PaisBean> _return = new LinkedList<ar.edu.ubp.das.ws.PaisBean>();
            ar.edu.ubp.das.ws.PaisBean _returnVal1 = new ar.edu.ubp.das.ws.PaisBean();
            _returnVal1.setCodPais("CodPais127411964");
            _returnVal1.setNomPais("NomPais411135318");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.PaisesWS#test()*
     */
    public java.lang.String test() { 
        LOG.info("Executing operation test");
        try {
            java.lang.String _return = "_return-1309555894";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
