package ar.edu.ubp.das.ws;

import java.util.LinkedList;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-19T19:41:43.527-03:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "PaisesWS")
@XmlSeeAlso({ObjectFactory.class})
public interface PaisesWS {

    @WebMethod(action = "urn:GetPaises")
    @RequestWrapper(localName = "getPaises", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetPaises")
    @ResponseWrapper(localName = "getPaisesResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetPaisesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public LinkedList<ar.edu.ubp.das.ws.PaisBean> getPaises() throws Exception_Exception;

    @WebMethod(action = "urn:Test")
    @RequestWrapper(localName = "test", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.TestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String test();
}
