
package ar.edu.ubp.das.fds.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-27T18:20:22.175-03:00
 * Generated source version: 3.1.7
 * 
 */
public final class ListaObrasSocialesCXF_ListaObrasSocialesCXFPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.fds.das.ubp.edu.ar/", "ListaObrasSocialesCXFService");

    private ListaObrasSocialesCXF_ListaObrasSocialesCXFPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ListaObrasSocialesCXFService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ListaObrasSocialesCXFService ss = new ListaObrasSocialesCXFService(wsdlURL, SERVICE_NAME);
        ListaObrasSocialesCXF port = ss.getListaObrasSocialesCXFPort();  
        
        {
        System.out.println("Invoking getObrasSociales...");
        try {
            java.util.List<java.lang.String> _getObrasSociales__return = port.getObrasSociales();
            System.out.println("getObrasSociales.result=" + _getObrasSociales__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
