package ar.edu.ubp.das.fds.cxf;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-27T18:20:22.274-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://cxf.fds.das.ubp.edu.ar/", name = "ListaObrasSocialesCXF")
@XmlSeeAlso({ObjectFactory.class})
public interface ListaObrasSocialesCXF {

    @WebMethod(action = "urn:GetObrasSociales")
    @RequestWrapper(localName = "getObrasSociales", targetNamespace = "http://cxf.fds.das.ubp.edu.ar/", className = "ar.edu.ubp.das.fds.cxf.GetObrasSociales")
    @ResponseWrapper(localName = "getObrasSocialesResponse", targetNamespace = "http://cxf.fds.das.ubp.edu.ar/", className = "ar.edu.ubp.das.fds.cxf.GetObrasSocialesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getObrasSociales() throws Exception_Exception;
}
