package ar.edu.ubp.das.fds.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-27T18:20:22.282-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ListaObrasSocialesCXFService", 
                  wsdlLocation = "http://localhost:8091/RecuperatorioServerCXF/ListaObrasSocialesCXF?wsdl",
                  targetNamespace = "http://cxf.fds.das.ubp.edu.ar/") 
public class ListaObrasSocialesCXFService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.fds.das.ubp.edu.ar/", "ListaObrasSocialesCXFService");
    public final static QName ListaObrasSocialesCXFPort = new QName("http://cxf.fds.das.ubp.edu.ar/", "ListaObrasSocialesCXFPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8091/RecuperatorioServerCXF/ListaObrasSocialesCXF?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ListaObrasSocialesCXFService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8091/RecuperatorioServerCXF/ListaObrasSocialesCXF?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ListaObrasSocialesCXFService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ListaObrasSocialesCXFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListaObrasSocialesCXFService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ListaObrasSocialesCXFService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ListaObrasSocialesCXFService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ListaObrasSocialesCXFService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ListaObrasSocialesCXF
     */
    @WebEndpoint(name = "ListaObrasSocialesCXFPort")
    public ListaObrasSocialesCXF getListaObrasSocialesCXFPort() {
        return super.getPort(ListaObrasSocialesCXFPort, ListaObrasSocialesCXF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListaObrasSocialesCXF
     */
    @WebEndpoint(name = "ListaObrasSocialesCXFPort")
    public ListaObrasSocialesCXF getListaObrasSocialesCXFPort(WebServiceFeature... features) {
        return super.getPort(ListaObrasSocialesCXFPort, ListaObrasSocialesCXF.class, features);
    }

}
