
package ar.edu.ubp.das.fds;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T18:29:21.346-03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class ServicioCategorias_PortTypeServer{

    protected ServicioCategorias_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.fds.ServicioCategorias();
        String address = "http://localhost:9090/ServicioCategoriasPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ServicioCategorias_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 