
package ar.edu.ubp.das.fds.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Mon Nov 06 18:01:59 ART 2017
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "getCategorias", namespace = "http://fds.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCategorias", namespace = "http://fds.das.ubp.edu.ar/")

public class GetCategorias {


}

