
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.fds;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T19:08:10.865-03:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ServicioCategoriasService",
                      portName = "ServicioCategoriasPort",
                      targetNamespace = "http://fds.das.ubp.edu.ar/",
                      wsdlLocation = "http://localhost:9090/ServicioCategoriasPort?wsdl",
                      endpointInterface = "ar.edu.ubp.das.fds.ServicioCategoriasWS")
                      
public class ServicioCategoriasPortImpl implements ServicioCategoriasWS {

    private static final Logger LOG = Logger.getLogger(ServicioCategoriasPortImpl.class.getName());

}
