package ar.edu.ubp.das.fds;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-11-06T19:08:10.880-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://fds.das.ubp.edu.ar/", name = "ServicioCategoriasWS")
public interface ServicioCategoriasWS {
}
