/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2018-04-25 23:50:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>Parcial 1</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/bootstrap-theme.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/style.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/validationForm.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3> Mi agenda</h3>\r\n");
      out.write("\t");

	if(request.getParameterMap().size() == 0) {
	
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form method=\"post\" id=\"formAgenda\" action=\"index.jsp\" class=\"col-md-12 order-md-1\" onsubmit=\"jForm.valid(event)\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("       \t\t\t<div class=\"col-md-2 mb-3\">\r\n");
      out.write("             \t\t<label for=\"ifecha\">Fecha</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" id=\"ifecha\" name=\"fecha\" class=\"form-control\" required value=\"\">\r\n");
      out.write("           \t\t</div>\r\n");
      out.write("         \t\t<div class=\"col-md-2 mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"iprioridad\">Prioridad</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"iprioridad\" name=\"prioridad\" class=\"form-control\" required onchange=\"jForm.selPrioridad(this)\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"A\">Alta</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"M\" selected=\"selected\">Media</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"B\">Baja</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t\t<div class=\"row\">\r\n");
      out.write("     \t\t\t<div class=\"col-md-4 mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"idescripcion\">Descripcion</label>\r\n");
      out.write("                \t<textarea cols=\"50\" rows=\"5\" id=\"idescripcion\" name=\"descripcion\" class=\"form-control\" placeholder=\"Ingrese la descripcion del evento\" required></textarea>\r\n");
      out.write("       \t\t\t</div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t\r\n");
      out.write("   \t\t\t<div class=\"row\">\r\n");
      out.write("         \t\t<div class=\"col-md-2 mb-3\">\r\n");
      out.write("         \t\t\t<div class=\"single-line\">\r\n");
      out.write("         \t\t\t  <label for=\"inotificarsi\">Notificar</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"notificar\" value=\"S\" id=\"inotificarsi\" checked=\"checked\" onchange=\"jForm.selNotificar(this)\">Si</label><br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"notificar\" value=\"N\" id=\"inotificarno\" onchange=\"jForm.selNotificar(this)\">No</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            \t<div class=\"col-md-2 mb-3\">\r\n");
      out.write("                \t<label for=\"iemail\">E-mail a notificar</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" id=\"iemail\" name=\"email\" class=\"form-control\" required  placeholder=\"Ingrese e-mail a notificar\" value=\"\" maxlength=\"255\">\r\n");
      out.write("       \t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" name=\"boton1\" class=\"btn btn-primary\">Agendar</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"reset\"  name=\"boton2\" class=\"btn btn-warning\">Limpiar</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	}
	else {

	HashMap<String,String> prioridades = new HashMap<String,String>();

	//SimpleDateFormat parser = new SimpleDateFormat("yyyy-MM-dd");
	//SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
	
	//Date fecha = parser.parse(request.getParameter("fecha"));

	prioridades.put("A", "Alta");
    prioridades.put("M", "Media");
    prioridades.put("B", "Baja");    

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\t<h3>Formulario de carga de datos</h3>\r\n");
      out.write("    <table class=\"table table-striped\">\r\n");
      out.write("       \t<colgroup>\r\n");
      out.write("       \t\t<col width=\"15%\" />\r\n");
      out.write("       \t</colgroup>\r\n");
      out.write("       \t<thead>\r\n");
      out.write("       \t\t<tr>\r\n");
      out.write("       \t\t <td align=\"right\">#</td>\r\n");
      out.write("             <td align=\"right\">Fecha</td>\r\n");
      out.write("             <td align=\"right\">Descripcion</td>\r\n");
      out.write("             <td align=\"right\">Prioridad</td>\r\n");
      out.write("             <td align=\"right\">Notificar a</td>\r\n");
      out.write("             <td align=\"right\">    </td>\r\n");
      out.write("        \t</tr>\r\n");
      out.write("       \t</thead>\r\n");
      out.write("       \t<tbody>\r\n");
      out.write("       \t\t<tr>\r\n");
      out.write("       \t\t\t<td align=\"right\">  </td>\r\n");
      out.write("       \t\t\t<td align=\"right\"> ");
      out.print( request.getParameter("fecha") );
      out.write("  </td>\r\n");
      out.write("       \t\t\t<td align=\"right\"> ");
      out.print( request.getParameter("descripcion") );
      out.write("  </td>\r\n");
      out.write("       \t\t\t<td align=\"right\"> ");
      out.print( prioridades.get(request.getParameter("prioridad")) );
      out.write(" </td>\r\n");
      out.write("       \t\t\t<td align=\"right\"> ");
      out.print( request.getParameter("email") );
      out.write("  </td>\r\n");
      out.write("       \t\t\t<td align=\"right\"> <button type=\"reset\" name=\"boton3\" onsubmit=\"jForm.click(event)\">Descartar</button>  </td>\r\n");
      out.write("       \t\t</tr>\r\n");
      out.write("       \t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
