
package asdasd.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Mon Nov 06 16:12:35 ART 2017
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "holaResponse", namespace = "http://asdasd/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "holaResponse", namespace = "http://asdasd/")

public class HolaResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

