
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Sun Nov 19 19:33:07 ART 2017
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "getPaisesResponse", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPaisesResponse", namespace = "http://ws.das.ubp.edu.ar/")

public class GetPaisesResponse {

    @XmlElement(name = "return")
    private java.util.LinkedList<ar.edu.ubp.das.bean.PaisBean> _return;

    public java.util.LinkedList<ar.edu.ubp.das.bean.PaisBean> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.LinkedList<ar.edu.ubp.das.bean.PaisBean> new_return)  {
        this._return = new_return;
    }

}

