
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Sun Nov 19 19:33:07 ART 2017
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "test", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "test", namespace = "http://ws.das.ubp.edu.ar/")

public class Test {


}

